name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "envs/global/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1
      PORTAL_BUCKET: ${{ vars.PORTAL_BUCKET }}
      CF_DIST_ID: ${{ vars.CF_DIST_ID }}
      BUILD_DIR: envs/global   # ← change from dist to envs/global
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify build/static folder exists
        run: |
          echo "Using BUILD_DIR='${BUILD_DIR}'"
          test -d "$BUILD_DIR" || { echo "Folder '$BUILD_DIR' not found"; exit 1; }
          ls -la "$BUILD_DIR"

      - name: Sync to S3
        run: |
          aws s3 sync "$BUILD_DIR"/ "s3://${PORTAL_BUCKET}/" --delete --exact-timestamps --no-progress

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id "${CF_DIST_ID}" --paths "/*"
