name: OIDC Check
on: { workflow_dispatch: {} }
permissions:
  id-token: write
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<YOUR-ACCOUNT-ID>:role/DeployRole-Dev
          aws-region: us-east-1
      - run: aws sts get-caller-identity
