name: Deploy Portal
on:
  push:
    branches: [ "main" ]
    paths:
      - "apps/portal/**"
      - ".github/workflows/portal-deploy.yml"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      PORTAL_BUCKET: <paste portal_bucket>
      DIST_ID: <paste cloudfront_distid>
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::713881788173:role/DeployRole-Dev
          aws-region: ${{ env.AWS_REGION }}

      - name: Ensure placeholder content
        run: |
          mkdir -p apps/portal
          echo '<!doctype html><html><body><h1>School Cloud Portal</h1></body></html>' > apps/portal/index.html

      - name: Sync to S3
        run: aws s3 sync apps/portal "s3://${{ env.PORTAL_BUCKET }}/" --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id "${{ env.DIST_ID }}" --paths "/*"
