name: Deploy Portal

on:
  push:
    branches: [ main ]
    paths:
      - "apps/portal/**"
      - ".github/workflows/portal-deploy.yml"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  # Keep these as-is if they match your current infra; otherwise change to your values.
  PORTAL_BUCKET: schoolcloud-portal-us-east-1
  DIST_ID: E3QFAE8UN3CQUW

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/portal/package.json

      - name: Install deps
        working-directory: apps/portal
        run: npm ci

      - name: Build
        working-directory: apps/portal
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::713881788173:role/DeployRole-Dev
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: |
          set -euxo pipefail
          aws s3 sync apps/portal/dist "s3://${PORTAL_BUCKET}/" --delete --only-show-errors

      - name: Invalidate CloudFront
        run: |
          set -euxo pipefail
          aws cloudfront create-invalidation --distribution-id "${DIST_ID}" --paths "/*"

